language: node_js
node_js:
  - "5"
before_script:
  - npm install -g gulp
  - npm install
script: gulp clean && gulp build && gulp service-worker && gulp manifest
before_deploy: sh load_key.sh
deploy:
  provider: script
  script: gulp ghpages
  skip_cleanup: true