language: node_js
node_js:
  - "5"
before_script:
  - npm install -g gulp
  - npm install
script: gulp clean && gulp build && gulp service-worker && gulp manifest
after_success:
  - git config --global user.name "Travis CI"
  - git config --global user.email "$COMMIT_AUTHOR_EMAIL"
before_deploy:
  - openssl aes-256-cbc -K $encrypted_9ba9e0c1817c_key -iv $encrypted_9ba9e0c1817c_iv -in id_rsa_travis.enc -out id_rsa_travis -d
  - chmod 600 id_ras_travis
  - eval "$(ssh-agent -s)"
  - ssh-add id_rsa_travis
deploy:
  provider: script
  script: gulp ghpages
  skip_cleanup: true